### ISSUE TITLE
Unable to obtain Kusama tokens from the faucet as described in the User Guid

### ISSUE THREAD

**Issue by Muhammad-Altabba** [kusamanetwork/userguide#104]
Hello,
I am following https://guide.kusama.network/en/latest/start/faucet/. But it seems that the Kusama Faucet bot is not working anymore. You may check the created issues for the last 5 days. There are no updates on any of them: ttps://github.com/kusamanetwork/faucet/issues

**Comment by laboon** [comment]
Thanks for reporting!  A recent runtime upgrade was incompatible with the faucet.  A fix is already in the works, which will be deployed on the Kusama network once it is running again.

**Comment by Swader** [comment]
@Muhammad-Altabba can you check if it works now? Should be fine.

**Comment by Muhammad-Altabba** [comment]
Thanks for resolving this.
