### ISSUE TITLE
Faucet Guide lacks important steps - saving vanity address

### ISSUE THREAD

**Issue by vfreudenhammer** [kusamanetwork/userguide#105]
The [Guide ](https://guide.kusama.network/en/latest/start/faucet/) is good and written so that even users new to Kusama can get onboarded easily.
However it lacks a step between 1) Generate an address and 2) Submit an issue. This is 1.2) Saving vanity address with private keys etc.
Furthermore a step 3) transferring ksm from Faucet address to initial address would be helpful as well.

Seems intuitive, but there are users (including myself) who do not understand the vanity address logic and therefor don´t receive the ksm they expect to get. The guide which is in itself dummy-proven, leaves this part out. Would be great, if it could be edited.

**Comment by chevdor** [comment]
See also https://github.com/polkadot-js/apps/issues/2119

**Comment by laboon** [comment]
Good catch and thank you for the feedback.  I will update this now.
