### ISSUE TITLE
Add claims contract address

### ISSUE THREAD

**Issue by soc1c** [kusamanetwork/userguide#2]
`0xXXXXXXXXXXX`

https://github.com/kusamanetwork/userguide/blob/master/docs/getstarted/method1.md#claim-your-ksma-with-mycrypto

**Comment by soc1c** [comment]
Is it `0xA7b099b5aA4F6d8209e6b58c0d5909D8ae1c00E7` ?

**Comment by joshua-mir** [comment]
That's the testnet address unfortunately

**Comment by joshua-mir** [comment]
Added in https://github.com/kusamanetwork/userguide/commit/f569a8f5612f2d8fa6e957d7b1fba279c694544a
